import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";


export const metadata: Metadata = {
  title: "Krishna Vaani",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ToastContainer
          position="top-center"
          theme="dark" />
        {children}
      </body>
    </html>
  );
}
